apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demystifying-aap-on-openshift-rh1-2027
  title: demystifying-aap-on-openshift-rh1-2027
  description: Hands on lab providing attendees with functioning AAP clusters,
    letting them break the cluster, then providing them with the troubleshooting
    steps to recover.
  annotations:
    ph.rhdp.io/content-type: lab
    ph.rhdp.io/deployment-mode: rhdp_published
    ph.rhdp.io/github-user: rl-rh
    ph.rhdp.io/owner: rlaroy@redhat.com
    ph.rhdp.io/migrated-repo: https://github.com/rhpds/demystifying-aap-on-ocp-showroom.git
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhpds/demystifying-aap-on-openshift-rh1-2027
    ph.rhdp.io/created-at: 2026-08-17T20:43:08.348Z
  tags:
    - publishing-house
    - lab
    - rhdp-published
    - migration
  links:
    - url: https://github.com/rhpds/demystifying-aap-on-openshift-rh1-2027
      title: Repository
      icon: github
    - url: https://devspaces.apps.ocpv-infra02.wdc07.infra.demo.redhat.com#https://github.com/rhpds/demystifying-aap-on-openshift-rh1-2027
      title: Open in DevSpaces
      icon: catalog
    - url: https://central-api-publishing-house.apps.ocpv-infra02.wdc07.infra.demo.redhat.com
      title: Central
      icon: dashboard
spec:
  type: content
  lifecycle: experimental
  owner: rhdp-team
  system: publishing-house
