---
namespace: rhpds
name: demystifying_aap
version: "1.0.0"
readme: README.md
authors:
  - "Ryan LaRoy <rlaroy@redhat.com>"
  - "Max Mitschke <mmitschk@redhat.com>"
  - "Ricardo Garcia Cavero <rgarciac@redhat.com>"
description: "Starter collection for this project's custom Ansible automation."
license: []
repository: "https://github.com/rhpds/demystifying-aap-on-openshift-rh1-2027"
