{{- if eq (int .Values.tenant.scenario) 4 }}
apiVersion: v1
kind: Secret
metadata:
  name: chatbot-configuration-secret
  namespace: {{ .Values.tenant.namespace }}
type: Opaque
stringData:
  chatbot_model: {{ .Values.alia.model }}
  chatbot_token: {{ .Values.alia.token }}
  chatbot_url: {{ .Values.alia.url }}
{{- end }}
